name: skype_clone
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http:
  photofilters: ^2.0.1

  shared_preferences: ^0.5.8
  firebase_core: ^0.5.0
  # For making request to firestore database
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  firebase_analytics: ^5.0.2
  firebase_storage: ^4.0.0
  photo_view: ^0.10.1

  # For handling permissions
  # permission_handler: ^4.1.0

  # For handling authentication via firebase
  
  

  # For handling google sign in
  google_sign_in: ^4.5.3

  # Shimmer effect library
  shimmer: 1.0.1

  # Gradient app bar
  gradient_app_bar: ^0.1.3
  

  # Emojies
  emoji_picker: ^0.1.0

  # image_picker
  image_picker: ^0.6.7+7

  # path provider
  path_provider: ^1.6.0

  # firebase storage


  # provider
  provider: ^4.0.3

  # cached network image
  cached_network_image: ^2.0.0

  # agora rtc engine
  agora_rtc_engine: ^1.0.8

  # permission handler
  permission_handler: 3.0.0

  # local storage
  hive: ^1.4.1+1
  sqflite: ^1.3.0
  image: ^2.1.14
  flutter_mobile_vision: ^0.1.3
  
  
  pdf: ^1.10.0
  google_fonts: ^1.1.0
  
  flutter_full_pdf_viewer: ^1.0.6
  # intl
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - app_logo.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
