name: skype_clone
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flare_flutter: ^2.0.6

  video_trimmer: ^0.2.7

  velocity_x: ^0.4.1
  barcode_scan: ^3.0.1
  http:
  local_auth: ^0.6.3+1
  audioplayers: ^0.16.1
  flutter_full_pdf_viewer: ^1.0.6
  shared_preferences: ^0.5.10
  firebase_core: ^0.5.0
  tuple: ^1.0.3
  # get: ^3.15.0
  font_awesome_flutter: ^8.10.0
  audio_recorder: ^1.0.2
  # For making request to firestore database
  cloud_firestore: ^0.14.0+2
  encrypt: ^4.0.3
  image_cropper: ^1.3.1
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  firebase_analytics: ^5.0.2
  firebase_storage: ^4.0.0
  photo_view: ^0.10.1
  video_player: ^0.10.12+5
  sounds: ^0.9.3
  clipboard: ^0.1.2+8
  carousel_slider: ^2.3.1
  firebase_ml_vision: ^0.9.7
  cached_video_player: ^1.0.3
  chewie: ^0.9.10

  flutter_ringtone_player: ^2.0.0
  agora_rtc_engine: ^3.1.2
  gallery_saver: ^2.0.1
 # For handling google sign in
  google_sign_in: ^4.5.3

  # Shimmer effect library
  shimmer: 1.0.1

  # Gradient app bar
  gradient_app_bar: ^0.1.3

  # Emojies
  emoji_picker: ^0.1.0

  # image_picker
  image_picker: ^0.6.7+11

  # path provider
  path_provider: ^1.6.0

  # firebase storage

  # provider
  provider: ^4.0.3

  # cached network image
  cached_network_image: ^2.0.0
  dio: ^3.0.10
  # agora rtc engine

  # permission handler
  permission_handler: ^3.0.0

  # local storage
  hive: ^1.4.1+1
  
  image: ^2.1.14
  flutter_mobile_vision: ^0.1.3
  advance_pdf_viewer: ^1.2.0
  sqflite: ^1.3.2+1
  pdf: ^1.11.2
  google_fonts: ^1.1.1
  file_picker: ^1.6.3+2

  # intl
  hexcolor: ^1.0.6
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logo.png
    - assets/call_pick.flr
    - assets/call_end.flr
    - assets/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
