name: chatify
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^6.1.1
  advance_pdf_viewer: ^2.0.0
  audioplayers: ^4.0.1
  permission_handler: ^10.2.0
  video_trimmer: ^2.0.1
  cached_network_image: ^3.0.0
  cached_video_player: ^2.0.0-dev.1
  video_player: ^2.1.10
  flutter_pdfview: ^1.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  chewie: ^1.5.0
  circular_reveal_animation: ^2.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.3
  # emoji_picker: any
  emoji_picker_flutter: ^1.5.4
  encrypt: ^5.0.0
  file: ^6.1.0
  file_picker: ^5.2.10
  firebase_analytics: ^10.2.1
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.6.2
  # firebase_ml_vision: ^0.12.0+2
 
  flare_flutter: ^3.0.0
  flutter_colorpicker: ^1.0.3
  flutter_ringtone_player: ^3.0.0
  # flutter_sound: ^8.1.9
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.0.0
  record: ^4.4.4
  geolocator: ^9.0.2
  flutter_sound_lite: ^8.2.5
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.0.3
  google_sign_in: ^6.1.0
  hexcolor: ^3.0.1
  hive: ^2.0.4
  dio: ^5.1.1
  http: ^0.13.3
  image_cropper: ^4.0.1
  image_picker: ^0.8.0+3
  intl: ^0.18.1
  local_auth: ^2.1.6
  path_provider: ^2.0.1
  pdf: ^3.3.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  shake: ^2.2.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  story_view: ^0.14.0
  swipe_to: ^1.0.2
  timeago: ^3.0.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/call_pick.flr
    - assets/call_end.flr
    - assets/chat_splash_screen.flr
    - assets/

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
