/*
  This class contains constants being used in the code
*/
class Constants {
  Constants._();
  static const String FIRST_COLOR = "first_color";
  static const String SECOND_COLOR = "second_color";
  static const String DARK_THEME = "darkTheme";
  static const String PROFILE_PHOTO = "profile_photo";
  static const String NAME = "name";
  static const String EMAIL = "email";
  static const String STATUS = "status";
  static const String GALLERY = "Gallery";
  static const String CAMERA = "Camera";
  static const String TEXT = "text";
  static const String MESSAGE_TYPE_IMAGE = "image";
  static const String TOKEN_CHANNEL = "TokenChannel";
  static const String IS_LOCKED = "isLocked";
  static const String IMAGE = "IMAGE";
  static const String BACKGROUND = "background";
  static const String LOCATION = "location";
  static const String AUDIO = "Audio";
  static const String MESSAGE_TYPE_CALL = "Call";
  static const String SLASH = "/";
  static const String IS_READ = "isRead";
  static const String FILE = "FILE";
  static const String MESSAGE = "message";
  static const String PASSWORD = "password";
  static const String SENDER_ID = "senderId";
  static const String RECEIVER_ID = "receiverId";
  static const String TYPE = "type";
  static const String TIMESTAMP = "timestamp";
  static const String PHOTO_URL = "photoUrl";
  static const String VIDEO_URL = "videoUrl";
  static const String AUDIO_URL = "audioUrl";
  static const String FILE_URL = "fileUrl";
  static const String IS_LOCATION = "isLocation";
  static const String POSITION = "position";
  static const String REPLY = "reply";
  static const String URL = "url";
  static const String FIREBASE_TOKEN = "firebase_token";
  static const String STATE = "state";
  static const String USER_NAME = "userame";
  static const String UID = "uid";
  static const String HAS_STATUS = "hasstatus";
  static const String CALLER_ID = "caller_id";
  static const String CALLER_NAME = "caller_name";
  static const String CALLER_PIC = "caller_pic";
  static const String CALL_RECEIVER_ID = "receiver_id";
  static const String RECEIVER_NAME = "receiver_name";
  static const String RECEIVER_PIC = "receiver_pic";
  static const String CHANNEL_ID = "channel_id";
  static const String HAS_DIALLED = "has_dialled";
  static const String ADDED_ON = "added_on";
  static const String CONTACT_ID = "contact_id";
  static const String CALL_STATUS = "call_status";
  static const String LOG_ID = "log_id";
  static const String CALL_LOGS_TABLE_NAME = "call_logs";
  static const String VIDEO = "VIDEO";
  static const String MESSAGE_TYPE_VIDEO = "video";
  static const String MESSAGE_TYPE_FILE = "file";
  static const String MESSAGE_TYPE_AUDIO = "audio";
}
